#Changes to any of the source files rebuilds all files
errorTutorial: customErrorHandling.cpp files/customErrorClass.cpp
	g++ -o errorTutorial customErrorHandling.cpp files/customErrorClass.cpp -I./files